server:
  port: 8080
spring:
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog.yaml"
  datasource:
    url: "jdbc:postgresql://${DATABASE_IP:127.0.0.1}:5432/book_demo"
    driverClassName: "org.postgresql.Driver"
    type: "com.zaxxer.hikari.HikariDataSource"
    username: "${DATABASE_USERNAME:postgres}"
    password: "${DATABASE_PASSWORD:casa1234}"