micronaut:
  profile: production
  application:
    name: bookDemoMicronaut
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/book_inventory
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'casa1234'
    dialect: POSTGRES
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/changelog.yaml'
---
jpa:
  default:
    entity-scan:
      packages: 'org.mvillabe.books.domain'
hibernate:
  physical_naming_strategy: "com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy"
  types:
    print:
      banner: false
---
gcp:
  project-id: "${PROJECT_ID}"
  credentials:
    encoded-key: "${ENCODED_CREDENTIALS}"
